config/routes.rb
Rails.application.routes.draw do
  devise_for :userrs
  root to: "home#index"
  # get  'userrs/index'
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/userr.rb
class Userr < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_employ, only: %i[ show]  
  def index
      @userrs = Userr.all
  end
  def show
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_userr
    @userr = Userr.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'User' , class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if userr_signed_in? %>
        <li class="nav-item">
        <%= link_to 'Edit Profile' , edit_userr_registration_path , class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        <%= link_to 'Sign out' , destroy_userr_session_path ,method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Show', userr_session_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to 'Sign in' , new_userr_session_path , class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign up' , new_userr_registration_path , class:"nav-link" %>
        </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if userr_signed_in? %>
<h1>Users List</h1>

<table class="table table-dark table-striped table-bordered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th class = "col-span "3" >Email</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= current_userr.fname %></td>
        <td><%= current_userr.lname %></td>
        <td><%= current_userr.email %></td>
        <td><%= current_userr.phone %></td>
      </tr>
  </tbody>
</table>
<%= link_to 'Back', :back ,class:"btn btn-outline-light btn-lg px-5" %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
  <%= render 'home/header' %>
 
  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <br/>
  <%= yield %>
  </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>